---
title: "Week 1 Homework"
output: html_notebook
---



Download the files:

```{r}

download_url <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
working_dir<-"~/coursera/exploratory-data-analysis/week1"
data_dir<-"data"
setwd(working_dir)
if (!dir.exists(data_dir)) {
    dir.create(data_dir)
}
fileURL <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
destFile<-paste(data_dir, "power_consumption.zip", sep="/")
if(!file.exists(destFile)) {
    download.file(fileURL, destfile = destFile, method="curl")
    dateDownloaded<-date()
    dateDownloaded
    unzip(destFile, exdir=data_dir)
}

```


Time to read the data. The data contains 2,075,259 rows and 9 colums. This will require a little bit less than 600MiB (~570MiB).

```{r}
datafile <- "./data/household_power_consumption.txt"
powerdata <- read.table(datafile, sep=";", header = TRUE, skip=66636, nrows=2880, na.strings = "?")
names(powerdata) <- c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
powerdata <- within(powerdata, {timestamp = strptime(paste(Date, Time), "%d/%m/%Y%H:%M:%S")})
```

## Plot 1

```{r}
hist(powerdata$Global_active_power, col="red", xlab="Global Active Power (kilowatts)", main="Global Active Power")
```

## Plot 2

```{r}
Sys.setlocale("LC_TIME", "en_US.UTF-8")
with(powerdata, plot(timestamp, Global_active_power, type="l", ylab = "Global Active Power (kilowatts)"))
```

## Plot 3

```{r}
Sys.setlocale("LC_TIME", "en_US.UTF-8")
with(powerdata, plot(timestamp, Sub_metering_1, type="n", ylab="Energy sub metering", xlab=""))
with(powerdata, lines(timestamp, Sub_metering_1, col="black"))
with(powerdata, lines(timestamp, Sub_metering_2, col="red"))
with(powerdata, lines(timestamp, Sub_metering_3, col="blue"))
legend("topright", lty = c(1,1), col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
```


## Plot 4

```{r}
Sys.setlocale("LC_TIME", "en_US.UTF-8")
par(mfrow = c(2,2))
with(powerdata, {
   plot(timestamp, Global_active_power, type="l", ylab = "Global Active Power")
   plot(timestamp, Voltage, type="l", ylab = "Voltage", xlab="datetime")
   plot(timestamp, Sub_metering_1, type="n", ylab="Energy sub metering", xlab="")
  lines(timestamp, Sub_metering_1, col="black")
  lines(timestamp, Sub_metering_2, col="red")
  lines(timestamp, Sub_metering_3, col="blue")
  legend("topright", box.lwd=0, lty = c(1,1), col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
  plot(timestamp, Global_reactive_power, type="l", ylab = "Global_reactive_power", xlab="datetime")
})
```



